spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wrokflow?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  redis:
    host: localhost
    port: 8443
logging.level:
  org.hibernate:
    SQL: debug
    type: trace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyewkrqwekkeWERkdfksazblYcfPQye08f7MGEWRweVA9XkHa
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 10407689
    key-store-type: PKCS12
    key-alias: spring
  port: 8443




