spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wrokflow?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          format_sql: true
  output:
    ansi:
      enabled: ALWAYS
logging.level:
  org.hibernate:
    SQL: debug
    type: trace
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyewkrqwekkeWERkdfksazblYcfPQye08f7MGEWRweVA9XkHa

